### ISSUE TITLE
Branch from master for V2 contract support

### ISSUE THREAD

**Issue by InoMurko** [omgnetwork/specs#18]
Plasma contracts V2 branch have some changes in types and in types of emmited events, we need to support these new interfaces in the new (long running) branch.

https://github.com/omgnetwork/plasma-contracts

**Comment by ayrat555** [comment]
I contacted @souradeep-das :
1. Changes between v1 and v2 contracts are located in this file - https://github.com/omgnetwork/plasma-contracts/blob/v2.0.0/CHANGELOG.md
2. `specs` already has a branch for v2 contracts - https://github.com/omgnetwork/specs/tree/master-v2. But it's not up to date. I'll try to make changes on top of that.

**Comment by InoMurko** [comment]
done
